name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc
    name: ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: ${{ matrix.target }}
          override: true
          default: true
          
      - name: Build
        run: cargo build --release
      
      - name: Strip & Rename (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          strip target/release/yiri-rs
          mv target/release/yiri-rs target/release/yiri-rs-${{ matrix.target }}
      
      - name: Rename (Windows)
        if: matrix.target == 'x86_64-pc-windows-msvc'
        run: |
          mv target/release/yiri-rs.exe target/release/yiri-rs-${{ matrix.target }}.exe
      
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: yiri-rs-${{ matrix.target }}
          path: target/release/yiri-rs-${{ matrix.target }}*
  
  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v2
        with:
          path: target/release
      - name: Release
        uses: softprops/action-gh-release@v1        
        with:
          files: |
            target/release/yiri-rs-amd64
